### ISSUE TITLE
Wrong locale

### ISSUE THREAD

**Issue by danperrout** [staticdev/irpf-cei#138]
![image](https://user-images.githubusercontent.com/3799060/86828313-737ea480-c069-11ea-8dfd-a19f6a3a2fc7.png)

![image](https://user-images.githubusercontent.com/3799060/86828272-5cd84d80-c069-11ea-8f1b-a2b4b923be06.png)
Please fix.

**Comment by staticdev** [comment]
* Add locale check
* Add error message to install pt_BR.UTF-8 (apt-get install language-pack-pt-base)
