### ISSUE TITLE
Fix read_xls arguments with pandas 1.1+

### ISSUE THREAD

**Issue by staticdev** [staticdev/irpf-cei#183]
Watch upstream issue: https://github.com/pandas-dev/pandas/issues/35753

**Comment by piradata** [comment]
> 
> 
> Watch upstream issue: [pandas-dev/pandas#35753](https://github.com/pandas-dev/pandas/issues/35753)

Hello @staticdev , it seems that this encoding parameter was never needed and was simple ignored as kwargs as this comment points.
https://github.com/pandas-dev/pandas/issues/35753#issuecomment-718843840
