### ISSUE TITLE
Você tem intenção  de também calcular os proventos(dividendos e juros sob capital próprio) ?

### ISSUE THREAD

**Issue by GabrielFelix10** [staticdev/irpf-cei#344]

**Comment by staticdev** [comment]
Posso colocar esse cálculo também, você já tem algo que calcula? PRs são sempre bem vindas.

**Comment by GabrielFelix10** [comment]
Pior que não tenho não , mas adoraria contribuir

**Comment by staticdev** [comment]
Posso tentar ajudar, mas normalmente não tenho que fazer esses cálculos pois compro ETFs.
