### ISSUE TITLE
Erro quando indexando o "Subreports within table/matrix cells"

### ISSUE THREAD

**Issue by GalaticStryder** [staticdev/irpf-cei#347]
Por algum motivo, meu arquivo do Excel vem com algumas colunas preenchidas com esse aviso, quando rodo o programa ele acusa o seguinte erro:

ValueError: time data 'Subreports within table/matrix cells are ignored.' does not match format '%d/%m/%y'

Tem uma opção de ignorar esse tipo de erro?

**Comment by staticdev** [comment]
@GalaticStryder que estranho.. tem como vc mudar os valores e mandar sua planilha anexada aqui na issue?

**Comment by GalaticStryder** [comment]
@staticdev Sim, upei no Drive: https://drive.google.com/file/d/1hK0F93Tpom7YnSjxZu-V6L1KFTACv3EI/view?usp=sharing

Ela é do BB-BI, que é multi corretora.

**Comment by GalaticStryder** [comment]
Então @staticdev eu fiz uns testes e rodou certinho depois que eu removi as linhas das demais corretoras e deixei só uma, só que isso acaba declarando cada ativo como sendo da primeira corretora que eu deixei. No caso, a ideia é adicionar o um forEach, pra que cada corretora no doc funcione com um indexador, e com somente uma no doc (XP, Rico, etc) com index 0, e BB-BI e outros bancos que usam esse tipo de corretagem, com index 0, 1, 2, etc. Só que as operações às vezes são abertas em uma corretora e fechadas em outra também, daí não seria qual seria a abordagem mais correta.

**Comment by staticdev** [comment]
@GalaticStryder esse caso realmente não estava testado (o mesmo ativo em corretoras diferentes). Como isso é declarado em geral, são 2 lançamentos em bens e direitos ou 1 só com a descrição das duas corretoras?

**Comment by staticdev** [comment]
@GalaticStryder vou fechar por ter 6 meses que estou esperando resposta.
