### ISSUE TITLE
Erro: locale pt_BR.utf8 não encontrado, confira a documentação para mais informações.

### ISSUE THREAD

**Issue by brunodoamaral** [staticdev/irpf-cei#466]
Recebi a mensagem do título quando tentei executar no Mac. Executando o comando `locale -a` descobri que no macOS o nome do locale é "pt_BR.UTF-8"

Seria possível adicionar um `if` ou um `except` para esta lingaguem?

Aliás, mt obrigado pelo seu projeto!

**Comment by staticdev** [comment]
Olá Bruno, obrigado pelo report, eu já estava fazendo uma melhoria na parte de localização que vai incluir também o locale para o Mac. Vou ver se sai uma versão hoje.

**Comment by staticdev** [comment]
@brunodoamaral tenta ai dps na versão 3.4.0.

**Comment by brunodoamaral** [comment]
@staticdev vlw Thiago, funcionou sim... e a poucas horas de encerrar o prazo pra entrega rs

Brigadão! []'s
