### ISSUE TITLE
Arrumar arredondamento do calculate_taxes

### ISSUE THREAD

**Issue by staticdev** [staticdev/irpf-cei#8]
O arredondamento em alguns casos está gerando um centavo de diferença. Investigar a forma de cálculo correta e corrigir.

* Remover TODO
* Descomentar teste com erro
* Alterar round_down

**Comment by staticdev** [comment]
Na verdade o erro está na taxa mensal #9.

**Comment by GalaticStryder** [comment]
Boa noite @staticdev, tudo bem? Parabéns pela sua iniciativa de criar esse programa, eu estou elaborando um programa parecido em javascript, só que prevendo o valor por operação e comparando com as notas de corretagem das minhas corretoras, XP e BB-BI. Só que por algum motivo eu estou tendo um erro de um centavo se comparado a nota de corretagem, dada pelo arredondamento, geralmente nas taxas de negociação (emolumentos) e liquidação. Em alguns casos um arredondamento para o mais próximo dá certo e bate com a nota da XP, já no BB-BI não, fica um centavo acima. Sabe qual o critério de arredondamento a ser utilizado nesses casos?

**Comment by staticdev** [comment]
Olá @GalaticStryder, vou fazer uma verificação mais a fundo mas não sei. Nesses casos, eu costumo mostrar meu cálculo e mandar para a corretora. Eles tem que explicar porque está dando diferença. Estou usando o arredondamento padrão pra 2 casas decimais do Python. Se você descobrir que o programa está realmente errado podemos reabrir essa issue e eu arrumo.
